### PR TITLE
Simplify and fix AC_CHECK_HEADERS for libzdb

### PR DESCRIPTION
**Pull request by tildeslash**

### CODE REVIEW

**Comment by tildeslash** [comment]
Please change configure script to check for the meta interface zdb.h instead

**Comment by CozC** [comment]
The request seems to be strait forward. 
As soon as I find some time I shall merge it. 
Thank you for your effort.

**Comment by thelounge-zz** [comment]
still don't build for dbmail-3.1 with libzdb-3.2.2 and no i can't happily upgrade to dbmail-3.2 in production with such a dead upstream and the expirience of 3.0 and 3.1 updates which took weeks to get stable running in real world usage

it#s vene not clear if 3.2 contains all patches from 3.1-2874f497fb429ed139e94342ca1c84325b20b3f1 + dbmail-prepend-headers-during-delivery.patch

+ echo 'Patch #2 (dbmail-libzb.patch):'
Patch #2 (dbmail-libzb.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file acinclude.m4
Hunk #1 succeeded at 285 (offset -3 lines).
patching file src/dbmail.h.in
Hunk #1 succeeded at 94 (offset -3 lines).
......................

configure: error: Could not find ZDB library.

**Comment by thelounge-zz** [comment]
this is just crazy for a point update of libzdb

In file included from conftest.c:31:
/usr/include/zdb/ResultSet.h:185:1: error: unknown type name 'bool'
  185 | bool ResultSet_next(T R);
      | ^~~~
/usr/include/zdb/ResultSet.h:203:1: error: unknown type name 'bool'
  203 | bool ResultSet_isnull(T R, int columnIndex);
      | ^~~~
In file included from conftest.c:33:
/usr/include/zdb/Connection.h:160:1: error: unknown type name 'bool'
  160 | bool Connection_ping(T C);
      | ^~~~
/usr/include/zdb/Connection.h:316:1: error: unknown type name 'bool'
  316 | bool Connection_isSupported(const char *url);
      | ^~~~
configure:4878: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "dbmail"
| #define PACKAGE_TARNAME "dbmail"
| #define PACKAGE_VERSION "3.1.17"
| #define PACKAGE_STRING "dbmail 3.1.17"
| #define PACKAGE_BUGREPORT "dbmail@dbmail.org"
| #define PACKAGE_URL ""
| #define PACKAGE "dbmail"
| #define VERSION "3.1.17"
| #define _GNU_SOURCE 'TRUE'
| #define DEFAULT_LOG_DIR "/usr/local/var/log"
| #define DM_PWD "/home/builduser/rpmbuild/BUILD/dbmail-2874f497fb429ed139e94342ca1c84325b20b3f1"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define SIEVE 1
| #define HAVE_MATH_H 1
| #define HAVE_MHASH_H 1
| #define HAVE_EVENT_H 1
| #define HAVE_OPENSSL_SSL_H 1
| /* end confdefs.h.  */
| 
| #include <URL.h>
| #include <ResultSet.h>
| #include <PreparedStatement.h>
| #include <Connection.h>
| #include <ConnectionPool.h>
| #include <SQLException.h>
| 
| 
| #include <SQLException.h>
configure:4878: result: no
configure:4899: error: Could not find ZDB library.

**Comment by CozC** [comment]
Salve,

There was a mention regarding the issue you are encountered mostly due to  
redefinition of some constants.
I never tried to build the 3.1, only DBMail 3.2.3  with libzdb 3.1, and is  
quite stable (no issues related to database, so no libzdb updates needed,  
personal opinion)
As soon as I find some time I'll take a look, but I feel it may require  
some changes to the code to make it work with the latest libzdb 3.2.2 :(

Have  a nice day.






On Wed, 01 Apr 2020 14:51:21 +0300, thelounge-zz  
<notifications@github.com> wrote:

>
> this is just crazy for a point update of libzdb
>
> In file included from conftest.c:31:
> /usr/include/zdb/ResultSet.h:185:1: error: unknown type name 'bool'
> 185 | bool ResultSet_next(T R);
> | ^~~~
> /usr/include/zdb/ResultSet.h:203:1: error: unknown type name 'bool'
> 203 | bool ResultSet_isnull(T R, int columnIndex);
> | ^~~~
> In file included from conftest.c:33:
> /usr/include/zdb/Connection.h:160:1: error: unknown type name 'bool'
> 160 | bool Connection_ping(T C);
> | ^~~~
> /usr/include/zdb/Connection.h:316:1: error: unknown type name 'bool'
> 316 | bool Connection_isSupported(const char url);
> | ^~~~
> configure:4878: $? = 1
> configure: failed program was:
> | / confdefs.h /
> | #define PACKAGE_NAME "dbmail"
> | #define PACKAGE_TARNAME "dbmail"
> | #define PACKAGE_VERSION "3.1.17"
> | #define PACKAGE_STRING "dbmail 3.1.17"
> | #define PACKAGE_BUGREPORT "dbmail@dbmail.org"
> | #define PACKAGE_URL ""
> | #define PACKAGE "dbmail"
> | #define VERSION "3.1.17"
> | #define _GNU_SOURCE 'TRUE'
> | #define DEFAULT_LOG_DIR "/usr/local/var/log"
> | #define DM_PWD  
> "/home/builduser/rpmbuild/BUILD/dbmail-2874f497fb429ed139e94342ca1c84325b20b3f1"
> | #define STDC_HEADERS 1
> | #define HAVE_SYS_TYPES_H 1
> | #define HAVE_SYS_STAT_H 1
> | #define HAVE_STDLIB_H 1
> | #define HAVE_STRING_H 1
> | #define HAVE_MEMORY_H 1
> | #define HAVE_STRINGS_H 1
> | #define HAVE_INTTYPES_H 1
> | #define HAVE_STDINT_H 1
> | #define HAVE_UNISTD_H 1
> | #define SIEVE 1
> | #define HAVE_MATH_H 1
> | #define HAVE_MHASH_H 1
> | #define HAVE_EVENT_H 1
> | #define HAVE_OPENSSL_SSL_H 1
> | / end confdefs.h. */
> |
> | #include <URL.h>
> | #include <ResultSet.h>
> | #include <PreparedStatement.h>
> | #include <Connection.h>
> | #include <ConnectionPool.h>
> | #include <SQLException.h>
> |
> |
> | #include <SQLException.h>
> configure:4878: result: no
> configure:4899: error: Could not find ZDB library.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by thelounge-zz** [comment]
it works perfectly with libzdb 3.2.0 all the time and that's what i don't get - semver anyone?

[root@mail:~]$ rpm -q dbmail
dbmail-3.1.17-13.fc31.20200204.rh.2874f497fb429ed139e94342ca1c84325b20b3f1.sandybridge.x86_64

[root@mail:~]$ rpm -q --changelog dbmail | head -n 2
* Tue Apr 09 2019 Reindl Harald <h.reindl@thelounge.net>
- rebuild against libzdb-3.2

**Comment by tildeslash** [comment]
>but I feel it may require some changes to the code to make it work with the latest libzdb 3.2.2 :( 

No, no changes are needed, just push the merge button and you'r good. The stuff I mentioned above are _warnings_ which I observed during build and _only_ for libzdb version 3.2 and 3.2.1. The code works fine despite these warnings.

**Comment by CozC** [comment]
Salve,

Taking into consideration the Tildeslash commit I took it on local  
machine, I applied the commit he has proposed and managed to compile trunk  
version of dbmail with the latest libzdb.
This is only a test, I believe a new release has to be made available.

So,

I will give the entire stack of steps mostly for posterity, in case some  
other users may end up an see entire process.

Apply those patches
- download the latest libzdb in our case libzdb 3.2.2
- compile it and install it
- wget
# cd /dbmail.patch (you patch folder)
# wget  
https://github.com/dbmail/dbmail/pull/22/commits/638eb4f21c97d1018360dab594f7e7437a626baf.patch
# wget  
https://github.com/dbmail/dbmail/pull/22/commits/f15636976cfa2b195e37be9016539d8213897b57.patch
# wget  
https://github.com/dbmail/dbmail/pull/22/commits/638eb4f21c97d1018360dab594f7e7437a626baf

- apply patch one by one
# cd ...dbmail...
# git apply /dbmail.patch/4a64f3c4a2239de106861ee5be81d120cf07dc94.patch
# git apply /dbmail.patch/f15636976cfa2b195e37be9016539d8213897b57.patch
# git apply /dbmail.patch/638eb4f21c97d1018360dab594f7e7437a626baf.patch

- recreate autoconfig
# cd ...dbmail....
# aclocal
# autoconf
# ./configure
# make all
# make install

And it should work.

However, I'm in agreement with you this is no way the preferred version to  
make an update. A new release of 3.1.7. build x should be made available.



On Wed, 01 Apr 2020 14:51:21 +0300, thelounge-zz  
<notifications@github.com> wrote:

>
> this is just crazy for a point update of libzdb
>
> In file included from conftest.c:31:
> /usr/include/zdb/ResultSet.h:185:1: error: unknown type name 'bool'
> 185 | bool ResultSet_next(T R);
> | ^~~~
> /usr/include/zdb/ResultSet.h:203:1: error: unknown type name 'bool'
> 203 | bool ResultSet_isnull(T R, int columnIndex);
> | ^~~~
> In file included from conftest.c:33:
> /usr/include/zdb/Connection.h:160:1: error: unknown type name 'bool'
> 160 | bool Connection_ping(T C);
> | ^~~~
> /usr/include/zdb/Connection.h:316:1: error: unknown type name 'bool'
> 316 | bool Connection_isSupported(const char url);
> | ^~~~
> configure:4878: $? = 1
> configure: failed program was:
> | / confdefs.h /
> | #define PACKAGE_NAME "dbmail"
> | #define PACKAGE_TARNAME "dbmail"
> | #define PACKAGE_VERSION "3.1.17"
> | #define PACKAGE_STRING "dbmail 3.1.17"
> | #define PACKAGE_BUGREPORT "dbmail@dbmail.org"
> | #define PACKAGE_URL ""
> | #define PACKAGE "dbmail"
> | #define VERSION "3.1.17"
> | #define _GNU_SOURCE 'TRUE'
> | #define DEFAULT_LOG_DIR "/usr/local/var/log"
> | #define DM_PWD  
> "/home/builduser/rpmbuild/BUILD/dbmail-2874f497fb429ed139e94342ca1c84325b20b3f1"
> | #define STDC_HEADERS 1
> | #define HAVE_SYS_TYPES_H 1
> | #define HAVE_SYS_STAT_H 1
> | #define HAVE_STDLIB_H 1
> | #define HAVE_STRING_H 1
> | #define HAVE_MEMORY_H 1
> | #define HAVE_STRINGS_H 1
> | #define HAVE_INTTYPES_H 1
> | #define HAVE_STDINT_H 1
> | #define HAVE_UNISTD_H 1
> | #define SIEVE 1
> | #define HAVE_MATH_H 1
> | #define HAVE_MHASH_H 1
> | #define HAVE_EVENT_H 1
> | #define HAVE_OPENSSL_SSL_H 1
> | / end confdefs.h. */
> |
> | #include <URL.h>
> | #include <ResultSet.h>
> | #include <PreparedStatement.h>
> | #include <Connection.h>
> | #include <ConnectionPool.h>
> | #include <SQLException.h>
> |
> |
> | #include <SQLException.h>
> configure:4878: result: no
> configure:4899: error: Could not find ZDB library.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu
